INSERT INTO car(id,name,type) VALUES (2,'AAAAAAAAAAAAA','CLASSIC');
INSERT INTO car(id,name,type) VALUES (5,'Chevrolet Corvette','CLASSIC');
INSERT INTO car(id,name,type) VALUES (14,'Ferrari FF','SPORTING');
INSERT INTO car(id,name,type) VALUES (15,'AUDI GT Spyder','SPORTING');
INSERT INTO car(id,name,type) VALUES (16,'Porsche Panamera','SPORTING');
INSERT INTO car(id,name,type) VALUES (17,'Lamborghini Aventador','SPORTING');
INSERT INTO car(id,name,type) VALUES (18,'Chevrolet Corvette Z06','SPORTING');
INSERT INTO car(id,name,type) VALUES (19,'BMW M5','SPORTING');
INSERT INTO car(id,name,type) VALUES (20,'Renault Megane RS Trophy','SPORTING');
INSERT INTO car(id,name,type) VALUES (21,'Maserati Grancabrio Sport','SPORTING');
INSERT INTO car(id,name,type) VALUES (22,'McLAREN MP4-12C','SPORTING');
INSERT INTO car(id,name,type) VALUES (23,'MERCEDES-BENZ C63 AMG','SPORTING');
INSERT INTO car(id,name,type) VALUES (24,'Bugatti Veyron','LUXE');
INSERT INTO car(id,name,type) VALUES (25,'Ferrari Enzo','LUXE');
INSERT INTO car(id,name,type) VALUES (26,'Lamborghini Reventon','LUXE');
INSERT INTO car(id,name,type) VALUES (27,'Leblanc Mirabeau','LUXE');
INSERT INTO car(id,name,type) VALUES (28,'Shelby Supercars Ultimate','LUXE');
INSERT INTO car(id,name,type) VALUES (29,'Pagani Zonda','LUXE');
INSERT INTO car(id,name,type) VALUES (30,'Koenigsegg CCX','LUXE');
INSERT INTO car(id,name,type) VALUES (31,'Mercedes SLR McLaren','LUXE');
INSERT INTO car(id,name,type) VALUES (32,'Rolls Royce Phantom','LUXE');
INSERT INTO car(id,name,type) VALUES (6,'Chevrolet Impala Coupe','CLASSIC');
INSERT INTO car(id,name,type) VALUES (7,'Cadillac Deville Convertible','CLASSIC');
INSERT INTO car(id,name,type) VALUES (8,'Chevrolet Bel-Air','CLASSIC');
INSERT INTO car(id,name,type) VALUES (9,'Cadillac Eldorado','CLASSIC');
INSERT INTO car(id,name,type) VALUES (10,'Ferrari 250 GTO','CLASSIC');
INSERT INTO car(id,name,type) VALUES (11,'Dodge Challenger','CLASSIC');
INSERT INTO car(id,name,type) VALUES (12,'Camaro SS 1969','CLASSIC');
INSERT INTO car(id,name,type) VALUES (13,'Ford Mustang 1976','CLASSIC');
INSERT INTO car(id,name,type) VALUES (33,'Lexus LFA','LUXE');

